local messageBus = require 'utils.message-bus'

local M = messageBus.new()
M.GAME_LOADED = 'GAME_LOADED'
M.KEY_PRESSED = 'KEY_PRESSED'
M.KEY_RELEASED = 'KEY_RELEASED'
M.MOUSE_PRESSED = 'MOUSE_PRESSED'
M.MOUSE_RELEASED = 'MOUSE_RELEASED'
M.WINDOW_FOCUS = 'WINDOW_FOCUS'
M.NEW_FLOWFIELD = 'NEW_FLOWFIELD'
M.CHARACTER_HIT = 'CHARACTER_HIT'
M.SET_TEXT_INPUT = 'SET_TEXT_INPUT'
M.GUI_TEXT_INPUT = 'GUI_TEXT_INPUT'
M.GUI_NODE_CLEANUP = 'GUI_NODE_CLEANUP'

return M