local Cooldown = require("utils.cooldown.cooldown")

local function test()
  local ts = socket.gettime() * 1000
  local cooldown = Cooldown:new(ts)
  local key = 'key-1'
  local duration = 0.1

  assert(cooldown:isReady(key), "cooldown should be ready because no cooldown exists")

  cooldown:set(key, duration)
  assert(not cooldown:isReady(key), "cooldown should not be ready")

  cooldown:setGlobalTime(ts + duration / 2)
  assert(not cooldown:isReady(key), "cooldown should not be ready")

  cooldown:setGlobalTime(ts + duration)
  assert(cooldown:isReady(key), "cooldown should be ready")

  cooldown:setGlobalTime(ts + duration + 1)
  assert(cooldown:isReady(key), "cooldown should be ready")
end

function init()
  test()
end

function on_reload()
  test()
end