local messageBus = require("utils.message-bus")
local perf = require("utils.perf")

local function multipleReducers()
	local msgBus = messageBus.new()
	local increaseDamageBy1 = function(msgType, msgValue)
		return msgValue + 1
	end
	msgBus.addReducer(increaseDamageBy1)
	msgBus.addReducer(increaseDamageBy1)

	local initialValue = 1
	local expectedValue = 3
	local handlerResult = nil
	local handler = function(msgType, finalDamage)
		handlerResult = finalDamage
	end
	local msgType = 'playerHit'
	msgBus.subscribe(handler)
	msgBus.send(msgType, initialValue)
	assert(handlerResult == expectedValue, 'expected '..expectedValue..' got '..tostring(handlerResult))
end

local function removeFunctions()
	local msgBus = messageBus.new()

	local reducerCallCount = 0
	local expectedReducerCallCount = 1
	local reducer = function(_, v, CLEANUP)
		reducerCallCount = reducerCallCount + 1
		return CLEANUP
	end
	msgBus.addReducer(reducer)

	local handlerCallCount = 0
	local expectedHandlerCallCount = 2
	local handler = function(msgType, finalValue, CLEANUP)
		handlerCallCount = handlerCallCount + 1
		return CLEANUP
	end
	local msgType = 'playerHit'
	msgBus.subscribe(handler)
	msgBus.send(msgType)
	msgBus.subscribe(handler)
	msgBus.send(msgType)

	assert(
		reducerCallCount == expectedReducerCallCount, 
		'expected call count to be '..expectedReducerCallCount..' got '..reducerCallCount
	)

	assert(
		handlerCallCount == expectedHandlerCallCount,
		'expected call count to be '..expectedHandlerCallCount..' got '..handlerCallCount
	)
end


local function perfTest()
	local msgBus = messageBus.new()

	local callCount = 0
	local function func(msgType, msgValue, CLEANUP)
		callCount = callCount + 1
		if callCount % 2 == 0 then
			return CLEANUP
		end
		return msgValue
	end
	
	local filterCount = 10000
	for i=1, filterCount do
		msgBus.addReducer(func)
	end

	local subscriberCount = 10000
	for i=1, subscriberCount do
		msgBus.subscribe(func)
	end

	local testSuite = function()
		local msg = {}
		local msgType = 'FOO'
		msgBus.send(msgType, msg)		
	end

	perf({
		title = filterCount..' filters and '..subscriberCount..' subscribers',
		done = function(timeTaken, title)
			print(title, timeTaken)
		end
	})(testSuite)()
	print('callCount', callCount)
end

local gettime = socket.gettime

local function test()
	multipleReducers()
	removeFunctions()
	-- perfTest()
end

function init(self)
	test()
end

function on_reload(self)
	test()
end
