local typeCheck = require("utils.type-check")

local function test()
	assert(
		typeCheck.validate('foo', typeCheck.STRING),
		'[typeCheck] string type check failed'
	)
	
	assert(
		typeCheck.validate(function() end, typeCheck.FUNCTION),
		'[typeCheck] function type check failed'
	)

	assert(
		typeCheck.validate({true}, typeCheck.TABLE),
		'[typeCheck] table type check failed'
	)

	assert(
		typeCheck.validate({foo = 'bar'}, function(v)
			return v.foo == 'bar', 'CUSTOM_TYPE'
		end),
		'[typeCheck] custom type check failed'
	)
end

function init(self)
	test()
end

function on_reload(self)
	test()
end
